# lmerge
# Makefile for lmerge
# File:/src/Makefile
# Date:2023.02.18
# By MIT License
# Copyright(C) 2021-2023 Ziyao.All rights reserved.

# Tools
INSTALL		= install

# Files
SRC		:= lmerge.lua

# Installing Target
INSTALL_DIR	= /usr/bin
INSTALL_FILE	= ${INSTALL_DIR}/lmerge

default: install

install:
	install -Dm 644 ${SRC} ${INSTALL_FILE}
